title: Apollo Engine
subtitle: Using Engine
versions:
  - '1'
sidebar_categories:
  null:
    - index
  Features:
    - features/schema-explorer
    - features/schema-history
    - features/performance
    - features/query-tracking
    - features/error-tracking
    - features/alerts
  Integrations:
    - integrations/slack
    - integrations/datadog
  Engine Proxy:
    - apollo-tracing
    - setup-node
    - setup-standalone
    - setup-heroku
    - setup-lambda
    - setup-virtual
    - proxy/guides
    - proxy/release-notes
    - proxy/troubleshooting
  Reference:
    - accounts
    - data-privacy
    - pricing
    - proxy-config
    - gdpr
    - upgrade-optics
    - 1.0-migration
github_repo: apollographql/engine-docs

apis:
  segment: awKBAQ3eIgXIChDoy119j6ab4R4tqcXr

nav_links:
  'Engine':
    url: http://engine.apollographql.com

url: https://www.apollographql.com/docs/engine/
root: /docs/engine/

public_dir: public/docs/engine
